Update to Pond / React Pond 3.0
actyx-contrib/todo-react pull request #4
Opened 2021-07-01 10:58 UTC by nicolas-actyx

2021-07-01 13:18 UTC, wwerner requested changes
LGTM and works, just add an `onError` to the pond handler, please.

2021-07-01 13:18 UTC, wwerner commented on src/index.js
> +      loadComponent={<Waiting />}
We just made `onError` required in the latest `react-pond`.
Let's add a reloading hander here like in https://github.com/Actyx/advanced-example/blob/master/src/order-management/root.tsx#L7

2021-07-01 13:25 UTC, rkuhn reviewed
The main purpose of this repo is to show the essence of what is needed to make todo-react persistent and collaborative. For that reason I deliberately refrained from making stylistic changes — there shouldn’t be anything superfluous in the diff. Now this PR updates the code, but it doesn’t create an updated diff (and doesn’t change the link, either). So I wonder what the best approach would be. Probably taking the same basis as #1 and creating the new minimal diff for the new react-pond release, and then updating the README in a separate PR to point to the new diff.

2021-07-01 15:42 UTC, wwerner commented
Ah, right.
So, I'd probably ...

1. Wipe `main`
2. Get the current `mdn/todo-react` 
3. Re-do the changes in a separate branch
4. Make a new PR

I could see to it early next week.
Walked through the changes in an office hour session anyway, should be quick then.

2021-07-14 09:39 UTC, rkuhn commented
Sorry for missing this: not sure what you mean by “wipe main” — the desired final state is that `master` equals upstream plus a single commit, where that single commit can easily be inspected and discussed by virtue of being done via a PR.

2021-07-14 09:43 UTC, wwerner commented
Sorry, my fault. It's `master` in this repo still.
So, more clearly:
* reset `master` to current `todo-react` state
* rebuild the Pond integration on Actyx v2/Pond v3 in new branch
* make PR from this against `master`

2021-07-14 11:01 UTC, wwerner commented
Can be closed in favor of #5 as discussed ☝️

2021-07-19 07:20 UTC, closed without merging